import = [
    "~/.config/alacritty/themes/themes/dracula.toml"
]

[env]
TERM = "xterm-256color"
SHELL = "/bin/zsh"

[shell]
program = "/bin/zsh"
args = ["--login", "-c", "tmux attach-session -t default || tmux new-session -s default"]

[window]
padding.x = 0
padding.y = 0
startup_mode = "Maximized"
decorations = "Buttonless"


[font]
normal.family = "MesloLGS Nerd Font Mono"
size = 19
offset.x = 0  # For letter spacing (default: 0)
offset.y = 0  # For line spacing (default: 0)

# Key bindings for Alacritty
[keyboard]
bindings = [
  { key = "Right", mods = "Alt", chars = "\u001BF" },
  { key = "Left",  mods = "Alt", chars = "\u001BB" },
]
#for video
# size = 35.0

# clear screen with ctrl+L
#[[key_bindings]]
#key = "L"
#mods = "Control"
#action = "ClearHistory"
