import = [
	#"~/.config/alacritty/themes/themes/dracula.toml"
	"~/.config/alacritty/themes/themes/monokai.toml"
	#"~/.config/alacritty/themes/themes/synthwave_84.toml"
]

[env]
TERM = "xterm-256color"

[window]
padding.x = 16
padding.y = 16
decorations = "Buttonless"
opacity = 0.8
blur = true
option_as_alt = "Both"

[font]
normal.family = "MesloLGS Nerd Font Mono"
size = 18


[keyboard]
bindings = [
  { key = "Right", mods = "Alt", chars = "\u001BF" },
  { key = "Left",  mods = "Alt", chars = "\u001BB" },
]
